//! WebSocket types for outgoing (client) WebSocket connections.
//!
//! The WebSocket connection lives in the runner (tokio task).
//! The runtime only manipulates an opaque WebSocketId and communicates
//! via message-passing channels.
//!
//! This design allows future decoupling: a Durable Object could
//! inherit a WebSocketId without moving the underlying TCP connection.

use tokio::sync::mpsc;

/// Unique identifier for a WebSocket connection.
///
/// Generated by the runtime scheduler, unique within a worker execution.
pub type WebSocketId = u64;

/// Message sent from JS to the WebSocket server.
#[derive(Debug)]
pub enum WebSocketOutgoing {
    /// UTF-8 text frame
    Text(String),
    /// Binary frame
    Binary(Vec<u8>),
    /// Close the connection
    Close { code: u16, reason: String },
}

/// Message received from the WebSocket server, delivered to JS.
#[derive(Debug)]
pub enum WebSocketIncoming {
    /// UTF-8 text frame
    Text(String),
    /// Binary frame
    Binary(Vec<u8>),
    /// Connection closed by server
    Closed { code: u16, reason: String },
    /// Error on the connection
    Error(String),
}

/// Established WebSocket connection handle.
///
/// Returned by [`crate::OperationsHandler::handle_websocket_connect`].
/// The runner owns the actual TCP/TLS connection; this struct provides
/// channels for bidirectional message passing.
pub struct WebSocketConnection {
    /// Send messages to the WebSocket server (JS -> WS)
    pub send_tx: mpsc::UnboundedSender<WebSocketOutgoing>,
    /// Receive messages from the WebSocket server (WS -> JS)
    pub recv_rx: mpsc::UnboundedReceiver<WebSocketIncoming>,
}
